### PR TITLE
introduced State

### PR DESCRIPTION
**Pull request by domnikl**
Hi @matthiasnoback,

I like the idea of TalisORM very much!
I introduced a State interface along with an ImmutableState implementation of it to prevent from undefined indices in the state array (using `Assert:keyExists`) or type errors (I implemented string and int here, maybe some other types would be helpful too). It's just an idea, just tell me if it's worth to continue working on.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Hey! Thanks for letting me know that, that's really encouraging!

I like your idea, but I have some doubts. First you should know that I've allowed PHP 5.6 for this project (see the README for the reasoning), which would at least require a bit of a rewrite... Second, the library doesn't support types for data from and to the DB in the first place (everything you get from the DB will be strings). That's because there's no type conversion like with Doctrine ORM. So, you'd have to manually cast anyway. Something we did in a current project that already uses this approach is that we at least used constants for the table column fields, which could help with refactoring and figuring out issues with wrong keys. I have to add that our database schema basically never changes, so maybe we have a different use case for this. Furthermore, I've liked the array for state so far, because it keeps things really simple (or "pragmatic" as they like to say hehe). So, what I'm saying is, I'm thinking about if this would be the right approach. As a last resort, we could always make the use of `State` optional, by allowing arrays or array-accessible objects to be used.

**Comment by domnikl** [comment]
@matthiasnoback thanks for your feedback! I understand that you want to keep it pragmatic and use arrays instead.

**Comment by matthiasnoback** [comment]
For now, yes. We'll see what this becomes. I'm happy to have you involved and hope that you haven't been discouraged by my words. By the way, I remember you said something about your own solution that went in the same direction; could you share it?

**Comment by domnikl** [comment]
@matthiasnoback it's no problem, just an idea I thought would fit in, but it's ok if you have other plans. Maybe something for the future. Yes, you can find it here: https://github.com/domnikl/aggregate but it's pretty rough and by now I implemented only the aggregate object hydration part, no real persistence by now.

**Comment by matthiasnoback** [comment]
Okay, it's good to hear that. Thanks for sharing the link; indeed, it looks like we're after more or less the same thing, cool!

**Pull request closed without merging**
