### PR TITLE
Improve type annotations

### PR DESCRIPTION
**Pull request by fransik**
Hi Matthias!

I came across your ORM after reading about it in Advanced Web Application Architecture (great book btw!). I decided to try it out in a sample project, and so far it's working really well, thank you! :+1: 

The only issue that I had with it is that phpstorm & phpstan complained about the incorrect type being returned by `AggregateRepository::getById()` when using it in my repository implementation. 

This PR fixes that, and while I was at it, I added some more type annotations so that it plays nicer with both phpstorm and phpstan (and potentially psalm?).

Let me know what you think :)

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks, that makes a lot of sense. Can you take a look at the failing analysis?

**Comment by fransik** [comment]
Sure no worries. I had a look and fixed the issues:

1) The PHPStan version used in CI didn't understand the PHPdoc syntax I used. This was due to Travis pulling the `talisorm/php72` and `talisorm/phpstan` images from the docker registry, but [these images](https://hub.docker.com/u/talisorm) are two years old (and thus containing an old version of PHPStan).
I changed the travis config to do a `docker-compose build` instead of pull. However it might be better to push the updated images to docker registry and change it back to pull again. CI builds will be faster that way.

2) Scrutinizer also didn't understand the PHPdoc syntax completely. The ones it didn't understand I prefixed with `phpstan-` so that PHPStan is able to use the advanced syntax, other tools can fallback to the regular syntax.

**Comment by matthiasnoback** [comment]
Nice work! I'll take a closer look ASAP. Do you have experience with Psalm as well, would it make sense to also add annotations that it can work with?

**Comment by fransik** [comment]
Thanks! I will have a play around with Psalm this weekend, see how it reacts :)

**Comment by matthiasnoback** [comment]
I've merged your work, thanks a lot!
In #31 I reverted the call to `docker-compose pull` because I have updated the images as you suggested.
Adding Psalm annotations will be nice, but there's no hurry and with your PR you have already added a lot of value to this project. Cool!

**Pull request closed without merging**
